In [1]:
import math

In [3]:
a=16
print(math.sqrt(a))
print(math.sin(a))

4.0
-0.2879033166650653


In [1]:
import numpy as np
nd=np.array([[1,2,3],[3,3,5,],[1,3,4],[3,6,7]])

In [2]:
nd.reshape(4,3)

array([[1, 2, 3],
       [3, 3, 5],
       [1, 3, 4],
       [3, 6, 7]])

In [10]:
f=np.array([1,2,3,4])

In [11]:
z=np.zeros((3,3))

In [16]:
h=np.arange(12)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.array(24)

array(24)

In [9]:
df=np.array([[1,2,3],[3,4,5]])#2 dimensional array

In [12]:
np.hsplit(df,1)

[array([[1, 2, 3],
        [3, 4, 5]])]

In [13]:
#df.shape(),df.ndim()
#df.reshape(2,2,3)/(3,2,2)

In [14]:
df.reshape(2,2,-1) # for dynamic data

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [16]:
num_arr=np.array([1,2,3,3,3,3,3,3,3,3,3,3])

In [20]:
num_arr.reshape(2,2,3)

array([[[1, 2, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [21]:
num_arr.reshape(-1)

array([1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
num_arr.reshape(2,2,-1)

array([[[1, 2, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [23]:
#np.add(A,B) to add two arrays,np.substract,np.multiply, np.divide,np.power(A,2)

In [24]:
x = np.array([i for i in range(10)])

In [25]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.where(x%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [27]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])