In [2]:
import numpy as np

In [2]:
arr=np.array([[4,3,2],[10,1,0],[12,3,55]])

In [3]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [12,  3, 55]])

In [4]:
np.amin(arr)#for minimum value in array

0

In [ ]:
np.amin(arr,axis=0) # or axis=1 then it would horizontal

In [5]:
np.max(arr)#np.amax(arr,axis=0)

55

In [6]:
np.median(arr)

3.0

In [7]:
np.mean(arr)

10.0

In [8]:
np.var(arr)#variance

267.55555555555554

In [9]:
np.std(arr)#standard deviation

16.35712552851373

In [10]:
np.percentile(arr,50)#to know value under percentile

3.0

In [12]:
deg = np.array([0,30,45,60,90])

In [13]:
np.sin(deg*np.pi/180)#to convert degree into radiance and #.cos and #.tan

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [14]:
#inverse of matrics
'''
arcisn
arccos
arctan
'''

'\narcisn\narccos\narctan\n'

In [15]:
arr = np.array([0.1,0.8,-2.2,-9.87])

In [16]:
np.floor(arr)#floor values #largest integer not greater than x.

array([  0.,   0.,  -3., -10.])

In [19]:
np.ceil(arr) # ceil values #Smallest integer not less than x.

array([ 1.,  1., -2., -9.])

In [20]:
#indexing and slicing

In [3]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [24]:
arr1[-3] # it will return 4

4

In [26]:
arr3[0,1,2] #it prints 3rd element of the second row of the first element

6

In [28]:
arr3[1,0,-1]

9

In [ ]:
#slicing arrays

In [5]:
arr1[1:]

array([2, 3, 4, 5, 6])

In [6]:
arr1[-3:-1]

array([4, 5])

In [10]:
arr2[1,1:]

array([5, 6])

In [11]:
arr2[0,-2:]

array([2, 3])

In [12]:
arr3[0,1:,1:]

array([[5, 6]])